Pipeline:
  name: Pipeline_10545
# pipeline resources
GitRepo:
  name: GitRepoRes
  type: GitRepo
  gitProvider: myGitHub
  path: {{.jfrog-pipelines.sourceRepository}}
  files:
    include: tests/core/helmdeploy/simplehelm.*
  branches:
    include: master

